// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk9nXhqDr3bdh6iVN2r3f2vlDd7trceUI',
    appId: '1:202184575633:web:05995d3fb4b9ab7daa4d30',
    messagingSenderId: '202184575633',
    projectId: 'fir-miner-b25ec',
    authDomain: 'fir-miner-b25ec.firebaseapp.com',
    storageBucket: 'fir-miner-b25ec.appspot.com',
    measurementId: 'G-LLJGRLSPPQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhPcWI9d18RAHXDa9ids7sr8pIf1CbuhM',
    appId: '1:202184575633:android:02bfbf3238f94ba4aa4d30',
    messagingSenderId: '202184575633',
    projectId: 'fir-miner-b25ec',
    storageBucket: 'fir-miner-b25ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQlG85LxBMJ6UR7oLFC5AiR8GFxpsulQo',
    appId: '1:202184575633:ios:c9512a13154a241aaa4d30',
    messagingSenderId: '202184575633',
    projectId: 'fir-miner-b25ec',
    storageBucket: 'fir-miner-b25ec.appspot.com',
    iosBundleId: 'com.example.firebaseminer',
  );
}
